Repository LDMX-Software/SimCore, pull requests merged in 2021-04, with the labels that each got.

#43 fixes to LHE generator to handle timing properly
  include/SimCore/LHEEvent.h
  src/SimCore/LHEEvent.cxx
  src/SimCore/LHEPrimaryGenerator.cxx
Labels: bug

#52 Gamma mumu
  include/SimCore/BiasOperators/GammaToMuPair.h
  python/bias_operators.py.in
  src/SimCore/BiasOperators/GammaToMuPair.cxx
Labels: enhancement, good first issue

#51 Update to reflect changes made to EventFile.
  python/generators.py.in
  src/SimCore/RootCompleteReSim.cxx
  src/SimCore/RootSimFromEcalSP.cxx
Labels: cleanup
